### ISSUE TITLE
Build fails with gradle's --parallel option

### ISSUE THREAD

**Issue by pdwinkel** [gesellix-docker/gradle-docker-plugin#23]
I've the following task:
```
task buildImage(type: DockerBuildTask, dependsOn: prepareImage) {
   imageName = nameWithVersion
   buildContextDirectory = file("${project.buildDir}/imageData")
}
```

The 'prepareImage' task creates/fills the ${project.buildDir}/imageData directory.

This works correct, but with the --parallel option the build fails:
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':docker:AppServer:buildImage'.
> java.io.FileNotFoundException: /home/peter/develop/tn2/products/docker/AppServer/build/tmp/tarBuildcontextForBuildImage/buildContext_tn2__app_server_1_0_0_1145-1.0.0.tgz (No such file or directory)
```

I think this fails because the tarBuildcontextForBuildImage does not depend on the 'prepareImage' task. During the build gradle outputs:

```
:docker:AppServer:tarBuildcontextForBuildImage UP-TO-DATE
:docker:AppServer:prepareImage
:docker:AppServer:buildImage FAILED
```

The tarBuildcontextForBuildImage task does not create the tgz because the input directory is not created/filled yet.
The tarBuildcontextForBuildImage task should depend on the tasks that the buildImage task depends on.

**Comment by gesellix** [comment]
I guess you're right. I'll look into it.

**Comment by gesellix** [comment]
@pdwinkel would like to try adding the following line to your build script? If that works for you, I would add the fix to the plugin:

```
tarBuildcontextForBuildImage.mustRunAfter prepareImage
```

Thanks!

**Comment by pdwinkel** [comment]
Yes, that works!

**Comment by gesellix** [comment]
@pdwinkel the fixed release is available as version `2015-02-15T13-45-26`.

**Comment by pdwinkel** [comment]
Works. Thx.
