### ISSUE TITLE
add .dockerignore support

### ISSUE THREAD

**Issue by gesellix** [gesellix-docker/gradle-docker-plugin#25]
don't let the plugin add .dockerignored files to the build context.

**Comment by gesellix** [comment]
@jtgasper3 please try the incubating task at `de.gesellix.gradle.docker.tasks.incubating.DockerBuildTask` instead of the usual DockerBuildTask. It should respect your `.dockerignore` contents and also keep any executable flags.
Your help with testing is much appreciated, thanks!

**Comment by gesellix** [comment]
the relevant release is available as https://plugins.gradle.org/plugin/de.gesellix.docker/2015-03-26T21-23-41

**Comment by jtgasper3** [comment]
@gesellix I'm not having success using the new release and excluding directories listed in the .dockerignore file. 
Here's my sample build... maybe I'm missing something.

build.gradle: 

```
plugins {
  id "de.gesellix.docker" version "2015-03-26T21-23-41"
}
apply plugin: 'java'

repositories {
    mavenCentral()
}

docker {
    dockerHost = 'https://192.168.59.103:2376'
}

import de.gesellix.gradle.docker.tasks.incubating.DockerBuildTask

task buildImage(type: DockerBuildTask) {
    imageName = "test/deleteme"
    buildContextDirectory = file('.')
}
```

Dockerfile:

```
FROM centos:7
```

.dockerignore:

```
build
large
```

In the `large` dir is a large file (150mb). It is continually included in the tar (which is 198 mb instead of almost nothing: `buildContext_test_deleteme/tmp/myLargeFile`. If I run the task a second time I get the following error:

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':tarBuildcontextForBuildImage'.
> This archives contains unclosed entries.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```

I suspect if the ignore worked properly this latter error wouldn't occur, but it might be worth explicitly ignoring the tar files that are built by the plugin with perhaps a flag to permit them... *just a thought*

Hopefully you can repo the issue.

**Comment by gesellix** [comment]
@jtgasper3 thanks for your feedback! I could now find and fix the issue with the non-ignored buildContext archive and your "large" file example. Please give the release `2015-03-30T19-03-02` a try (as soon as it's available via plugin portal or use the configuration like https://github.com/gesellix-docker/gradle-docker-plugin-example/blob/master/build.gradle#L17). I've added a dedicated test case similar to yours at the example project https://github.com/gesellix-docker/gradle-docker-plugin-example/tree/master/build-with-dockerignore

**Comment by gesellix** [comment]
@jtgasper3 did you already have a chance to test?

**Comment by jtgasper3** [comment]
@gesellix Thanks for the reminder... 

It's closer, but still not at parity with native `.dockerignore`...  With the native support, a directory (and its contents) can be excluded with `dirname` or `dirname/`, but I had to use `dirname/*` to ignore my very large file/directory.

**Comment by gesellix** [comment]
@jtgasper3 thanks for your patience, the issue should now be fixed with `2015-04-08T22-16-48`, you'll need to change your imports from
```
import de.gesellix.gradle.docker.tasks.incubating.DockerBuildTask
```

to
```
import de.gesellix.gradle.docker.tasks.DockerBuildTask
```

Please give it another try and drop me a short note if it worked, thanks! :)

**Comment by jtgasper3** [comment]
That appears to be working as expected. Nice work!

**Comment by gesellix** [comment]
@jtgasper3 thanks for beta testing :+1:
