### ISSUE TITLE
Gradle clean <task> fails, because temporary directory is created at configure phase

### ISSUE THREAD

**Issue by mmannerm** [gesellix-docker/gradle-docker-plugin#27]
`de.gesellix.gradle.docker.tasks.DockerBuildTask$_configureTarBuildContextTask_closure2.doCall(DockerBuildTask.groovy:66)` calls getTemporaryDir() while configuring the TarBuildContextTask, making the tar-ball file fail on creation (because the directory build/tmp/buildImage is missing, because it got wiped by the `clean`).

You should either use the getTemporaryDirFactory as suggested below, or just hit `mkdirs()` on the File before you try to write to it in the actual implementation phase.

Similar to issue https://issues.gradle.org/browse/GRADLE-2313
> The issue is that useJUnit() creates a temp dir (during configuration), that is used during execution.
> If `clean` runs before test, this dir will be wiped out. The solution will be to use  AbstractTask#getTemporaryDirFactory() instead of using getTemporaryDir().

**Comment by gesellix** [comment]
@mmannerm thanks for filing the issue and your helpful hints, the fix is available with https://plugins.gradle.org/plugin/de.gesellix.docker/2015-04-10T20-09-03
